services:
  django:
    container_name: django
    image: django:1
    build: ./srcs/django/
    depends_on:
      - postgresql
    ports:
      - '8000:8000'
    volumes:
      - django_volume:/project
    env_file:
      - .env
    networks:
      - transcendence
    # restart: always

  postgresql:
    container_name: postgresql
    image: postgresql:1
    build: ./srcs/postgresql/
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - transcendence
    # restart: always

  nginx:
    container_name: nginx
    image: nginx:1
    build: ./srcs/nginx/
    ports:
      - '443:443'
    # volumes:
    #   - postgresql_volume:/var/lib/postgresql/data
    env_file:
      - .env
    depends_on:
      - postgresql
    networks:
      - transcendence
    # restart: always

volumes:
  django_volume:
    name: django_volume
    driver: local
    driver_opts:
      type : none
      device: /home/user/ecole_42/transcendence/data/django_volume
      # device: /Users/yuuuuki/ecole_42/transcendence/data/django_volume
      o : bind
  postgresql_volume:
    name: postgresql_volume
    driver: local
    driver_opts:
      type : none
      device: /home/user/ecole_42/transcendence/data/postgresql_volume
      # device: /Users/yuuuuki/ecole_42/transcendence/data/postgresql_volume
      o : bind

networks:
  transcendence:
    driver: bridge
